### ISSUE TITLE
重打开网易云 音量都会拉满

### ISSUE THREAD

**Issue by Marce1ek** [BetterNCM/LibFrontendPlay#1]
安装之后 第一次重载插件 就会出现 只有每次重开网易云也一样
本来音量在三分之一位置 重开后输出的音量直接拉满 但是音量条还是显示在三分之一位置 要每次手动调整音量
麻烦看下❤

**Comment by hoshinokiseki** [comment]
Betterncm版本1.0.0
LibFrontendPlay版本0.1.0
遇到了相同的问题

**Comment by MicroCBer** [comment]
fixed
