### ISSUE TITLE
更新1.10后BetterNCM不识别插件

### ISSUE THREAD

**Issue by Lu-Tianxing** [BetterNCM/LibFrontendPlay#12]
如题，不识别该插件，插件市场与列表显示未下载，多次重载无效，plugins文件夹内存在LibFrontendPlay-1.1.0.plugin

**Comment by MicroCBer** [comment]
请尝试更新到 BetterNCM 测试通道最新版，检查问题是否修复

**Comment by MicroCBer** [comment]
https://github.com/MicroCBer/BetterNCM/commit/77f688d1addf429192f2c3062ad1f4bdaa21e65f

理论上应该在这修复了

**Comment by Lu-Tianxing** [comment]
> 请尝试更新到 BetterNCM 测试通道最新版，检查问题是否修复

更新到betterncm测试版后能正常读取了，但是正式版不行

**Comment by MicroCBer** [comment]
嗯，这是本体的一个问题
