### ISSUE TITLE
Plugin Loading Error: [json.exception.type_error.302] type must be object, but is array

### ISSUE THREAD

**Issue by Ginsakura** [BetterNCM/LibFrontendPlay#13]
`log.log`File:`Plugin Loading Error: [json.exception.type_error.302] type must be object, but is array`

系统: Windows 10 Enterprise 22H2
网易云: 2.10.8(Build 200917)
BetterNCM: 1.1.0
PluginVersion: LibFrontendPlay 1.1.0

安装后重启网易云,LFP插件不会被装载,BetterNCM的日志提示为类型错误

**Comment by MicroCBer** [comment]
#12
