### ISSUE TITLE
部分歌曲无法播放

### ISSUE THREAD

**Issue by MisakaOvOMikoto** [BetterNCM/LibFrontendPlay#2]
启用该插件后部分歌曲无法播放，进度条卡在加载中显示0秒。没有发现不能播放的歌曲规律。。有的VIP歌曲能播放而有的非VIP歌曲也无法播放。已经排除其他插件冲突问题，单独安装这个插件也会出现问题。
很奇怪的一点，无法播放的歌曲仅限于我自己的歌单，而且绝大多数歌曲都是已经下载的本地音乐。而私人FM里面的歌曲都可以正常播放。
我大概查清问题所在了。。在线播放没有问题，但下载的歌曲如果是网易云专有的NCM格式文件就无法播放了，可惜大部分VIP歌曲都是NCM格式，禁用NCM缓存看来也无法对本地文件生效。希望未来能够支持NCM格式文件？

**Comment by FR0Z3** [comment]
我这边买过的曲子而且缓存过了，还是会出现问题。切换曲子的话甚至也会有不能播放的问题。
![console_output](https://user-images.githubusercontent.com/33184021/213862143-aab324df-f415-46ae-994d-35dee771228e.png)

**Comment by MicroCBer** [comment]
请清空网易云缓存。网易云缓存过的歌曲会导致网易云不重新请求播放URL，也就无法播放。

**Comment by BackWheel** [comment]
> 请清空网易云缓存。网易云缓存过的歌曲会导致网易云不重新请求播放URL，也就无法播放。

我也遇到了类似的问题，尽管清空了网易云的缓存还是会导致音乐无法播放，是不是需要连下载过的音乐文件都得删除？

**Comment by MicroCBer** [comment]
> > 请清空网易云缓存。网易云缓存过的歌曲会导致网易云不重新请求播放URL，也就无法播放。
> 
> 我也遇到了类似的问题，尽管清空了网易云的缓存还是会导致音乐无法播放，是不是需要连下载过的音乐文件都得删除？

更新到最新版插件再试试

**Comment by MicroCBer** [comment]
本地.ncm文件现在会直接忽略，可能日后会添加支持
