### ISSUE TITLE
支持杜比全景音的音乐无法播放

### ISSUE THREAD

**Issue by github-tang** [BetterNCM/LibFrontendPlay#3]
启用betterncm之后，支持杜比全景音的音乐如果打开 杜比全景音 就会无法播放（网易云音乐本身运行正常，只是听不了歌）

BetterNCM 版本：1.0.0
网易云音乐版本：2.10.6
网易云音乐 Patch 版本：5ad43a6

LibFrontendPlay版本：0.1.0

**Comment by MicroCBer** [comment]
无法修复
