### ISSUE TITLE
[ Bug ] 底部音乐栏的时间进度显示问题

### ISSUE THREAD

**Issue by VincentDirac** [BetterNCM/LibFrontendPlay#8]
<b>Bug内容</b>
你好，我发现一个问题，安装此插件以后，如果是从头播放曲目，那么随着播放的进行，音乐栏显示的时间是可以正常增加的，但是如果我用鼠标点击中间某个位置，从中间开始播放，那么音乐兰显示的时间就会一直保持为点击处的时间点，不会增加。除了时间不增加以外，进度条也不走了。卸载此插件后没有这种问题。
<b>触发条件</b>
安装了本插件，且从中间而不是从头开始播放歌曲。
<b>安装的BetterNCM版本</b>
1.0.1
<b>LibFrontendPlay版本</b>
0.1.0
<b>网易云音乐版本</b>
2.10.6

**Comment by MicroCBer** [comment]
安装 FluentProgressBar
